from setuptools import setup, find_packages

setup(
    name="quest_pcm",
    version="1.1.0",
    description="A production cost modeling tool with enhanced storage models.",
    author="Dilip Pandit (dpandit@sandia.gov)",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "colorama==0.4.6",
        "contourpy==1.3.3",
        "coramin==0.1.1",
        "cycler==0.12.1",
        "et_xmlfile==2.0.0",
        "fonttools==4.61.1",
        "iniconfig==2.3.0",
        "kiwisolver==1.4.9",
        "matplotlib==3.10.8",
        "narwhals==2.14.0",
        "networkx==3.6.1",
        "numpy==2.3.5",
        "openpyxl==3.1.5",
        "packaging==25.0",
        "pandas==2.3.3",
        "pillow==12.0.0",
        "plotly==6.5.0",
        "pluggy==1.6.0",
        "ply==3.11",
        "Pygments==2.19.2",
        "pyomo==6.9.4",
        "pyparsing==3.2.5",
        "pyside6==6.6.2",
        "pytest==9.0.2",
        "python-dateutil==2.9.0.post0",
        "pytz==2025.2",
        "PyYAML==6.0.3",
        "rainflow==3.2.0",
        "scipy==1.16.3",
        "seaborn==0.13.2",
        "six==1.17.0",
        "tzdata==2025.3",
        "gridx_egret @ git+https://github.com/grid-parity-exchange/Egret.git@c6f4f2c5c18727aabf2c20ce1edae941d2b6f843",
    ],
    python_requires=">=3.11",
    entry_points={
        "console_scripts": [
            "pcm=pcm.__main__:main",
        ],
    },
)
