DA_lookahead_periods: 12
Flexible Ramp Down: timeseries
Flexible Ramp Up: timeseries
NonSpinning Reserve: timeseries
RT_lookahead_periods: 6
RT_resolution: 5
Regulation Down: fixed
Regulation Up: fixed
Spinning Reserve: fixed
Supplemental Reserve: timeseries
System Reserve: timeseries
baseMVA: 100.0
branch_contingency: false
end_date: 07/10/2020
fixed_renewable_types:
- RTPV
load_timeseries_aggregation_level: area
mipgap: 0.001
output_interval: at_once
plotly_plots: true
renewable_generator_types:
- PV
- RTPV
- HYDRO
- WIND
run_RTSCED_as: LP
solver: gurobi
start_date: 07/10/2020
storage_AS_participation_level: 4
thermal_generator_types:
- CT
- CC
- STEAM
- NUCLEAR
